package com.elvis.optimizationtask.ui.view.components;

import com.elvis.optimizationtask.algorithm.maxcut.MaxCutType;
import com.elvis.optimizationtask.algorithm.maxcut.MaxCutWeightFactory;
import com.elvis.optimizationtask.algorithm.tsp.TSPType;
import com.elvis.optimizationtask.algorithm.tsp.TSPWeightFactory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by User: el
 * Date: 11.11.12
 * Time: 11:24
 */
public class TSPDecompositionUIElement {
    private JComboBox maxCutType;
    private JComboBox tspType;
    private JPanel contentPane;

    public TSPDecompositionUIElement() {
        for (String maxCutType : MaxCutWeightFactory.getInstance().getMaxCutList()) {
            this.maxCutType.addItem(maxCutType);
        }
        for (TSPType tspType : TSPWeightFactory.getTSPList()) {
            this.tspType.addItem(tspType);
        }
    }

    public MaxCutType getMaxCutType() {
        return (MaxCutType) maxCutType.getSelectedItem();
    }

    public TSPType getTSPType() {
        return (TSPType) tspType.getSelectedItem();
    }


    public JPanel getContentPane() {
        return contentPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Max Cut alg");
        contentPane.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        maxCutType = new JComboBox();
        contentPane.add(maxCutType, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("TSP alg");
        contentPane.add(label2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tspType = new JComboBox();
        contentPane.add(tspType, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("TSP Decomposition:");
        contentPane.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        label1.setLabelFor(maxCutType);
        label2.setLabelFor(tspType);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
